### PR TITLE
DDP-7219 make study builder UI more presentable

### PR DESCRIPTION
**Pull request by aglushko-broad**
image

### CODE REVIEW

**Comment by alextanlan** [comment]
Overall, looks great!

**Comment by alextanlan** [comment]
Noticed a small issue - a picklist option not updated (change detection did not work immediately).
please take a look: 

https://user-images.githubusercontent.com/7396837/144048950-793926aa-f16e-44aa-b9fa-8bf6a70b72d4.mp4

**Comment by aglushko-broad** [comment]
> Noticed a small issue - a picklist option not updated (change detection did not work immediately). please take a look:
> 
>  screen-capture.mp4

It will be fixed as part of this comment https://github.com/broadinstitute/ddp-angular/pull/953#issuecomment-982105373

**Comment by MocanaAtBroad** [comment]
Definitely major improvement in appearance! And the resizing is helpful.

**Comment by MocanaAtBroad** [comment]
A change request: I think we can get rid of the  "You got x blocks" message in the preview? Had that as debug when was trying to figure out how preview would get updated. We are definitely past that now!

**Comment by aglushko-broad** [comment]
> A change request: I think we can get rid of the "You got x blocks" message in the preview? Had that as debug when was trying to figure out how preview would get updated. We are definitely past that now!

done!

**Review by alextanlan — APPROVED** [review]

**Pull request merged**
