### PR TITLE
DDP-5789: Add language selector to ddp-mbc

### PR DESCRIPTION
**Pull request by alextanlan**

### CODE REVIEW

**Review by aglushko-broad — APPROVED** [review]

**Review by MocanaAtBroad — COMMENTED** [review]
Not seeing the selector. How do I test it?

**Comment by MocanaAtBroad** [comment]
> Not seeing the selector. How do I test it?

OK. Got the selector to show up by hacking LanguageServiceAgent/getConfiguredLanguages method to:
```typescript
return of([{languageCode: 'en', displayName: 'English', isDefault: true} , {languageCode: 'es', displayName: 'Espanol', isDefault: false} ] as StudyLanguage[]);
```
If you have some other way to do this, please leave a note.

**Comment by MocanaAtBroad** [comment]
The language switching does appear to be working and code changes look reasonable.

**Comment by alextanlan** [comment]
> If` you have some other way to do this, please leave a note.

I did the same for testing, mocked `LanguageServiceAgent.getConfiguredLanguages` response.

**Review by MocanaAtBroad — APPROVED** [review]

**Pull request merged**
