### PR TITLE
DDP-6349: Add new members to about us page

### PR DESCRIPTION
**Pull request by aleksey-kuznetsov**

### CODE REVIEW

**Review by charlottedye — CHANGES_REQUESTED** [review]
It looks like the names should be in alphabetical order (both from looking at the spreadsheet and from looking at how the names are currently arranged).

**Comment by aleksey-kuznetsov** [comment]
> It looks like the names should be in alphabetical order (both from looking at the spreadsheet and from looking at how the names are currently arranged).

Correct! Thanks for that.

**Comment by yufengwng** [comment]
What's the status of this?

**Review by yufengwng — APPROVED** [review]
Looks good on my end. Let's merge.

**Pull request merged**
