### PR TITLE
DDP-6732 set language via URL param

### PR DESCRIPTION
**Pull request by aglushko-broad**

### CODE REVIEW

**Review by MocanaAtBroad — DISMISSED** [review]
I am going to approve it because it gets us the basic functionality, but I would like to have the language selected via URL to be "sticky". i.e., if I click on a link from say /faq?lang=es to go to the about us page, I want to see the about us page ins Spanish.

**Comment by aglushko-broad** [comment]
> I am going to approve it because it gets us the basic functionality, but I would like to have the language selected via URL to be "sticky". i.e., if I click on a link from say /faq?lang=es to go to the about us page, I want to see the about us page ins Spanish.

fixed!

**Review by alextanlan — DISMISSED** [review]

**Review by MocanaAtBroad — DISMISSED** [review]
Going to approve again as it does what it what need it to do. BUT there is one improvement that if really easy do do, it would be nice:
if language is changed from selector, drop the lang=es or whatever query param.
I just like to see that URLs match what you see.
Again, if this a big change/risky messes up what you did, leave it alone. But if just a question of tweaking a line of code in the language selector component or something like that, then let's do it.

**Comment by aglushko-broad** [comment]
> Going to approve again as it does what it what need it to do. BUT there is one improvement that if really easy do do, it would be nice:
> if language is changed from selector, drop the lang=es or whatever query param.
> I just like to see that URLs match what you see.
> Again, if this a big change/risky messes up what you did, leave it alone. But if just a question of tweaking a line of code in the language selector component or something like that, then let's do it.

done!

**Review by MocanaAtBroad — APPROVED** [review]
Nice!

**Pull request merged**
