### PR TITLE
DDP-5636: Fix a css bug in About Your Child activity

### PR DESCRIPTION
**Pull request by alextanlan**
This change is [Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)

### CODE REVIEW

**Review by EdPokhvalin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alextanlan, @fat23cat, and @MocanaAtBroad)

___
*[ddp-workspace/projects/ddp-osteo/src/styles/activity.scss, line 377 at r1](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUOw_Kp4_j5gZjXQsoM:-MUOw_Kp4_j5gZjXQsoN:b-ybl4m5) ([raw file](https://github.com/broadinstitute/ddp-angular/blob/581146b810f565972abae09bfb378929a99f6070/ddp-workspace/projects/ddp-osteo/src/styles/activity.scss#L377)):*
> ```SCSS
>         display: flex !important;
>         flex-direction: column !important;
>         align-items: initial !important;
> ```

I am a little confused by the presence of a large number of "!important" marks. I know it is not a problem of this review (and possibly not a problem at all) but I believe we may do something with that (like use CSS variables or just restructure our styles).

**Review by alextanlan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @EdPokhvalin, @fat23cat, and @MocanaAtBroad)

___
*[ddp-workspace/projects/ddp-osteo/src/styles/activity.scss, line 377 at r1](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUOw_Kp4_j5gZjXQsoM:-MUPQ1nU4bao67fXVkvB:bmdoahf) ([raw file](https://github.com/broadinstitute/ddp-angular/blob/581146b810f565972abae09bfb378929a99f6070/ddp-workspace/projects/ddp-osteo/src/styles/activity.scss#L377)):*
<details><summary><i>Previously, EdPokhvalin wrote…</i></summary><blockquote>

I am a little confused by the presence of a large number of "!important" marks. I know it is not a problem of this review (and possibly not a problem at all) but I believe we may do something with that (like use CSS variables or just restructure our styles).
</blockquote></details>

Should we create a separate task for that ? Like 'css optimization'

**Review by EdPokhvalin — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @alextanlan, @fat23cat, and @MocanaAtBroad)

___
*[ddp-workspace/projects/ddp-osteo/src/styles/activity.scss, line 377 at r1](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUOw_Kp4_j5gZjXQsoM:-MUStOmRCfrM_jNbQO4H:b4esi1q) ([raw file](https://github.com/broadinstitute/ddp-angular/blob/581146b810f565972abae09bfb378929a99f6070/ddp-workspace/projects/ddp-osteo/src/styles/activity.scss#L377)):*
<details><summary><i>Previously, alextanlan wrote…</i></summary><blockquote>

Should we create a separate task for that ? Like 'css optimization'
</blockquote></details>

I think so but it shouldn't have high priority

**Review by EdPokhvalin — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fat23cat and @MocanaAtBroad)

**Review by MocanaAtBroad — CHANGES_REQUESTED** [review]
Change looks good and works in mobile. Looks like we have same bug in other projects. Wherever we have a composite question that is aligned horizontally we are likely to have this problem. I have updated ticket to include a couple other cases.
My suggestion is to apply the change to all projects. When you do this, please update the JIRA ticket to alert Kiara that she should double check other projects as well. 

> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-:-MUTWFkQ-7zkaBX7xLng:b-cy5vtn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fat23cat)

**Review by EdPokhvalin — COMMENTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @alextanlan and @fat23cat)

___
*[ddp-workspace/projects/ddp-angio/src/styles/activity.scss, line 26 at r2](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUnk2_2-PVb9jXBkGTO:-MUnk2_2-PVb9jXBkGTP:byzv55c) ([raw file](https://github.com/broadinstitute/ddp-angular/blob/3783477843e78f8819be9ad81fd6b96336643558/ddp-workspace/projects/ddp-angio/src/styles/activity.scss#L26)):*
> ```SCSS
> }
> 
> @media screen and (max-width: 560px) {
> ```

Why 560px? This is not the [standard width|https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/]. Did you get this number empirically?

**Review by EdPokhvalin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @alextanlan and @fat23cat)

___
*[ddp-workspace/projects/ddp-angio/src/styles/activity.scss, line 26 at r2](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUnk2_2-PVb9jXBkGTO:-MUnlL1V5Z73fVsC1Z2C:boadggm) ([raw file](https://github.com/broadinstitute/ddp-angular/blob/3783477843e78f8819be9ad81fd6b96336643558/ddp-workspace/projects/ddp-angio/src/styles/activity.scss#L26)):*
<details><summary><i>Previously, EdPokhvalin wrote…</i></summary><blockquote>

Why 560px? This is not the [standard width|https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/]. Did you get this number empirically?
</blockquote></details>

Sorry, meant [this link](https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more)

**Review by alextanlan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @EdPokhvalin and @fat23cat)

___
*[ddp-workspace/projects/ddp-angio/src/styles/activity.scss, line 26 at r2](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUnk2_2-PVb9jXBkGTO:-MUoJlg09KYlZxXGTt14:b-uz2g6z) ([raw file](https://github.com/broadinstitute/ddp-angular/blob/3783477843e78f8819be9ad81fd6b96336643558/ddp-workspace/projects/ddp-angio/src/styles/activity.scss#L26)):*
<details><summary><i>Previously, EdPokhvalin wrote…</i></summary><blockquote>

Sorry, meant [this link](https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more)
</blockquote></details>

I copied it from ddp-osteo\..\welcome.component.scss. Also we have the same value at ddp-testboston\..\activity.scss.
Not sure that we have some requirements about breakpoints. 
I just tried to have the consistency.

**Review by alextanlan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @EdPokhvalin and @fat23cat)

*[a discussion](https://reviewable.io/reviews/broadinstitute/ddp-angular/459#-MUoLBQnDZwV57_ZsnAf:-MUoLBQnDZwV57_ZsnAg:b-p6uioq) (no related file):*
>  to apply the change to all projects. 
Marco, I fixed the same issue for ddp-angio, ddp-brain and ddp-esc accordingly. Also updated the JIRA ticket.

---

**Review by MocanaAtBroad — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/broadinstitute/ddp-angular/459)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @EdPokhvalin and @fat23cat)

**Pull request merged**
