### PR TITLE
DDP-5718: Study messages

### PR DESCRIPTION
**Pull request by aleksey-kuznetsov**
This PR introduces:
- slightly redesigned dashboard
- "Study Messages" section on dashboard
- conversion of workflows to study messages

P.S. `MEDICAL_RECORDS_LAST_RECEIVED` field is not yet present in DSM nor ES, so mapping in `workflow-key.ts` file will be changed once this field is added.

### CODE REVIEW

**Review by yufengwng — COMMENTED** [review]
Looks good as far as I can tell.

**Comment by charlottedye** [comment]
I don't know what I'm doing wrong, but I keep trying to run this and I can create an account and do the survey just fine, but I can't get the dashboard to work: it always shows the loading screen and I get this backend error, which is weird because I'm running this locally and obviously I'm not even running DSM locally:


` [qtp629067090-191] ERROR o.b.d.r.GetDsmParticipantStatusRoute Something went wrong during fetching the workflow statuses from ES for study RGP and participant 1VMYTZY75D3IDH2ZIYSM.
java.net.ConnectException: Connection refused
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:959)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696)
	at org.elasticsearch.client.RestHighLevelClient.get(RestHighLevelClient.java:736)
	at org.broadinstitute.ddp.route.GetDsmParticipantStatusRoute.getDataFromEs(GetDsmParticipantStatusRoute.java:104)
	at org.broadinstitute.ddp.route.GetDsmParticipantStatusRoute.process(GetDsmParticipantStatusRoute.java:77)
	at org.broadinstitute.ddp.route.GetDsmParticipantStatusRoute.handle(GetDsmParticipantStatusRoute.java:62)
	at org.broadinstitute.ddp.route.GetDsmParticipantStatusRoute.handle(GetDsmParticipantStatusRoute.java:36)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at org.broadinstitute.ddp.jetty.JettyConfig$JettyCustomRemoteAddrHeaderHandler.doHandle(JettyConfig.java:94)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	... 1 common frames omitted
`

I'm going to keep trying but if I don't get to this today, this will be why...

**Comment by yufengwng** [comment]
@charlottedye Did you have ES running locally? The dashboard statuses depends on the GetDsmParticipantStatusRoute API endpoint, which in turn grabs data from ES. If you're not connecting to your local ES, make sure you're able to connect to whatever ES instance you have in your config file.

**Comment by charlottedye** [comment]
Okay, so that part's legitimate.  I started elasticsearch locally and it fixed that problem.  Now I'm getting this: `message: "Participant CV9V7KWZ2GBB8F38KYCH or study RGP not found"` in the frontend.  Should I just run this against the dev database and dev ElasticSearch?  Is that my problem?

**Comment by charlottedye** [comment]
I'm going to see if I can get this to work tomorrow.  I'll try running it against dev and see if that works

**Comment by yufengwng** [comment]
@charlottedye Try the following tomorrow:

* In your backend config file, make sure to set
    * `runScheduler: true`
    * `elasticsearch.syncEnabled: true`
    * and have `elasticsearchUrl` point to your local ES instance.
* Then run Housekeeping locally.

This will start up Housekeeping, which will start up a job scheduler, which will run the DataSyncJob, which will write data to your local ES instance. When you create new local user, it should write data to ES so you should no longer see error about "not found". Then, you can probably play around by manually editing `workflows` data in the participant ES document to test out the statuses.

**Comment by aleksey-kuznetsov** [comment]
@charlottedye I had some problems running it locally as well so I had to connect to `dev` backend.

Quick note: you won't see any messages initially, only after you change some of the associated fields in DSM only then it is going to be present in the `workflows` list.

**Review by charlottedye — APPROVED** [review]
Looks good to me!

**Pull request merged**
