### PR TITLE
DDP-4397: Update videos on the osteo home page

### PR DESCRIPTION
**Pull request by fat23cat**
Just added real links on videos

### CODE REVIEW

**Review by zyme — CHANGES_REQUESTED** [review]
This new alternative approach does look faster and gives us more control, which is nice!

However, we need to stick with youtube hosting here--even with discounts, the financial cost of us hosting and egressing content isn't something we can afford.

**Comment by fat23cat** [comment]
> This new alternative approach does look faster and gives us more control, which is nice!
> 
> However, we need to stick with youtube hosting here--even with discounts, the financial cost of us hosting and egressing content isn't something we can afford.

Okay... How about Google Drive? We can store videos there, we only need to make these videos public, or it also will create additional financial costs?

**Review by MocanaAtBroad — APPROVED** [review]
Code looks good and is working correctly for me, so I am approving.
However, one thing that I am not sure we can control (let's investigate options); the initial/static image that is shown when the video has not yet played.
In the top video, the image seems OK to me, but the bottom one looks like the girl got caught in mid-blink; a few frames earlier or later would be OK.
As I understand it, Youtube by default show a the frame that is the very middle of the stream. Maybe there is a way to select a different one?

**Comment by fat23cat** [comment]
> Code looks good and is working correctly for me, so I am approving.
> However, one thing that I am not sure we can control (let's investigate options); the initial/static image that is shown when the video has not yet played.
> In the top video, the image seems OK to me, but the bottom one looks like the girl got caught in mid-blink; a few frames earlier or later would be OK.
> As I understand it, Youtube by default show a the frame that is the very middle of the stream. Maybe there is a way to select a different one?

Youtube doesn't allow to change video's 'poster', we can do it only with `<video>`

**Comment by MocanaAtBroad** [comment]
It appears that the uploader of the video can select one of three frames that YouTube generates to be the "poster". They can also create custom "thumbnails" where they can do whatever they want for the poster. Might be worth letting CountMeIn folks of their options.

**Pull request merged**
