### PR TITLE
PEPPER-1349 DSM clinical order page update 

### PR DESCRIPTION
**Pull request by ssettipalli**
Add new columns to DSM clinical order page.
Query from backend and add to UI display and download

### CODE REVIEW

**Review by zyme — APPROVED** [review]
Looks good to me.  We'll probably want to fiddle with sizing of the json columns so that they don't eat up all the screen space.

**Comment by ssettipalli** [comment]
Screenshot 2024-06-27 at 10 18 36 AM

**Comment by ssettipalli** [comment]
Screenshot 2024-06-27 at 1 34 55 PM

**Comment by ssettipalli** [comment]
json columns are at the end and all other existing columns looks decent (attached screen shots) . Might need to scroll to view last json element fully

**Pull request merged**
