### PR TITLE
Add sign out button once logged in

### PR DESCRIPTION
**Pull request by aleksey-kuznetsov**
A small fix to add "Sign Out" button underneath "Dashboard" link once user is logged in.

### CODE REVIEW

**Review by charlottedye — CHANGES_REQUESTED** [review]
The sign out button looks good but something went wrong with the header on the activity page.
Screen Shot 2021-02-11 at 1 23 52 PM

**Comment by aleksey-kuznetsov** [comment]
Please, check PR once again, I wasn't able to find any issues related to styling.

**Review by charlottedye — APPROVED** [review]
Sorry; wrong PR

**Review by charlottedye — APPROVED** [review]
Looks good now!

**Pull request merged**
