### PR TITLE
Osteo images optimization

### PR DESCRIPTION
**Pull request by fat23cat**
I applied compression optimizations to .svg, .png and .jpg files
It allows saving good quality and reduces total images size on 30%(~1MB -> ~700KB)
I used Google's tool for .png and .jpg optimization - https://squoosh.app/
And https://compressor.io/ for .svg

### CODE REVIEW

**Comment by MocanaAtBroad** [comment]
Did you try `ddp-workspace/projects/ddp-osteo/dist/assets/images/osteo-team.png`?

**Review by MocanaAtBroad — APPROVED** [review]
Nice weight savings. And everything looks just as good! Just had one question in comments.

**Comment by fat23cat** [comment]
> Did you try `ddp-workspace/projects/ddp-osteo/dist/assets/images/osteo-team.png`?

I didn't optimize this, because it's the final picture, Erin will share another later.

**Comment by MocanaAtBroad** [comment]
> > Did you try `ddp-workspace/projects/ddp-osteo/dist/assets/images/osteo-team.png`?
> 
> I didn't optimize this, because it's the final picture, Erin will share another later.

You mean it is not yet the final picture, correct? Brought it up because this is the larget png we have.

**Comment by fat23cat** [comment]
> > > Did you try `ddp-workspace/projects/ddp-osteo/dist/assets/images/osteo-team.png`?
> > 
> > 
> > I didn't optimize this, because it's the final picture, Erin will share another later.
> 
> You mean it is not yet the final picture, correct? Brought it up because this is the larget png we have.

Ooops, correct. Made a typo :)

**Pull request merged**
