### PR TITLE
DDP-5151: Replace the existing Brain Angular app with the Brain Pediatrics app

### PR DESCRIPTION
**Pull request by fat23cat**

### CODE REVIEW

**Comment by fat23cat** [comment]
@MocanaAtBroad, I have one concern here: if we merge this PR and later this week we will need to urgently cut the new release branch and deploy to prod, do we have the possibility **don't** deploy frontend brain app? I believe we don't want to show an updated app ahead of time.

**Comment by MocanaAtBroad** [comment]
> @MocanaAtBroad, I have one concern here: if we merge this PR and later this week we will need to urgently cut the new release branch and deploy to prod, do we have the possibility **don't** deploy frontend brain app? I believe we don't want to show an updated app ahead of time.

If this is the case, then let's not merge it yet and keep it in this branch. I have not heard of a release plan for this. Have you?

**Comment by MocanaAtBroad** [comment]
Front page logo is missing/mistyped:
Screen Shot 2020-10-20 at 12 38 24 PM

**Comment by fat23cat** [comment]
> If this is the case, then let's not merge it yet and keep it in this branch. I have not heard of a release plan for this. Have you?

Yes, I have. Maybe the next week or the beginning of November.

**Review by MocanaAtBroad — COMMENTED** [review]
Looks good! Let's not merge!

**Review by MocanaAtBroad — DISMISSED** [review]

**Review by MocanaAtBroad — APPROVED** [review]

**Pull request merged**
